
obj-$(CONFIG_ADSP_FACTORY) += adsp_factory.o ssc_core.o
obj-$(CONFIG_LSM6DSM_FACTORY) += lsm6dsl_accel.o lsm6dsl_gyro.o
obj-$(CONFIG_AK09918_FACTORY) += ak09918_mag.o
obj-$(CONFIG_VCNL36863_FACTORY) += vcnl36863_light.o vcnl36863_prox.o
obj-$(CONFIG_VEML3328_FACTORY) += veml3328_light.o
